# Project: cpp
# Makefile created by Steve Chang
# Date modified: 2025.06.01

LIBNAME = libmain.a

DIR = src

SUBDIR =

INCLUDE = \

SRCS = $(wildcard *.cpp)

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
